[project]
name = "dcd-mapping"
description = "Map MaveDB scoresets to reference sequences"
authors = [
    {name = "Alex Handler Wagner", email = "Alex.Wagner@nationwidechildrens.org"},
    {name = "Jeremy Arbesfeld", email = "todo@todo.com"},
    {name = "James Stevenson", email = "James.Stevenson@nationwidechildrens.org"},
    {name = "Samriddhi TODO", email = "todo@todo.com"}
]
readme = "README.md"
version = "0.0.1"
license = { file = "LICENSE" }
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dcd_mapping"]

[project.optional-dependencies]
test = []
dev = [
    "ruff",
    "black",
    "pre-commit"
]

[project.urls]
Homepage = 'https://www.varianteffect.org/'
Documentation = 'https://github.com/ave-dcd/dcd_mapping/README.md'
Source = 'https://github.com/ave-dcd/dcd_mapping'

[tool.black]
line-length = 88
extend-exclude = "^/docs/source/conf.py"

[tool.ruff]
# pycodestyle (E, W)
# Pyflakes (F)
# flake8-annotations (ANN)
# flake8-quotes (Q)
# pydocstyle (D)
# pep8-naming (N)
# isort (I)
select = ["E", "W", "F", "ANN", "Q", "D", "N", "I"]

fixable = ["I"]

# D205 - blank-line-after-summary
# D400 - ends-in-period
# D415 - ends-in-punctuation
# ANN101 - missing-type-self
# ANN003 - missing-type-kwargs
# E501 - line-too-long
ignore = ["D205", "D400", "D415", "ANN101", "ANN003", "E501"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.per-file-ignores]
